# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-09 20:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=30)),
                ('number_of_climbs', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Boulder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boulders', to='climbs.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
                ('anchor', models.IntegerField()),
                ('lead', models.BooleanField()),
                ('toprope', models.BooleanField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='climbs.Area')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='climbs.Color')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='climbs.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Setter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='setter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='climbs.Setter'),
        ),
        migrations.AddField(
            model_name='boulder',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boulders', to='climbs.Color'),
        ),
        migrations.AddField(
            model_name='boulder',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boulders', to='climbs.Grade'),
        ),
        migrations.AddField(
            model_name='boulder',
            name='setter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boulders', to='climbs.Setter'),
        ),
        migrations.AddField(
            model_name='area',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='climbs.Gym'),
        ),
    ]
