# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-15 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('date_retired', models.DateField(null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='climbs.Area')),
            ],
        ),
        migrations.CreateModel(
            name='ClimbType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.BooleanField()),
                ('anchor', models.IntegerField(null=True)),
                ('lead', models.BooleanField()),
                ('toprope', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('current', 'current'), ('retired', 'retired'), ('in progress', 'in progress')], max_length=11)),
            ],
        ),
        migrations.AddField(
            model_name='climb',
            name='climb_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='climbs.ClimbType'),
        ),
        migrations.AddField(
            model_name='climb',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='climbs.Color'),
        ),
        migrations.AddField(
            model_name='climb',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='climbs.Grade'),
        ),
        migrations.AddField(
            model_name='climb',
            name='setter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='climbs.Setter'),
        ),
        migrations.AddField(
            model_name='climb',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='climbs.Status'),
        ),
    ]
