# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-16 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0002_auto_20180315_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor', models.IntegerField(null=True)),
                ('lead', models.BooleanField()),
                ('toprope', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='climb',
            name='climb_type',
        ),
        migrations.DeleteModel(
            name='ClimbType',
        ),
        migrations.AddField(
            model_name='climb',
            name='climb_route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='climbs.ClimbRoute'),
        ),
    ]
