# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-16 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0003_auto_20180316_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='climb',
            field=models.IntegerField(choices=[(1, 'Boulder'), (2, 'Route')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='climb',
            name='climb_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='climbs.ClimbRoute'),
        ),
        migrations.AlterField(
            model_name='climb',
            name='date_retired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='climbroute',
            name='anchor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
