# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-16 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0004_auto_20180316_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_spread', to='climbs.Grade')),
            ],
        ),
        migrations.AddField(
            model_name='gym',
            name='spread',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='the_gym', to='climbs.Spread'),
            preserve_default=False,
        ),
    ]
