# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-16 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0005_auto_20180316_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='spread',
        ),
        migrations.AddField(
            model_name='spread',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='the_spread', to='climbs.Gym'),
            preserve_default=False,
        ),
    ]
