# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-18 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0006_auto_20180316_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='setter',
            name='current_gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='climbs.Gym'),
            preserve_default=False,
        ),
    ]
