# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-21 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0007_setter_current_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='climbs.Area'),
        ),
        migrations.AlterField(
            model_name='climb',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='climbs.Color'),
        ),
        migrations.AlterField(
            model_name='climb',
            name='setter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='climbs.Setter'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('current', 'current'), ('retired', 'retired'), ('in progress', 'in progress'), ('in queue', 'in queue')], max_length=11),
        ),
    ]
