# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-21 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0008_auto_20180321_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climb',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='climbs.Area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='climb',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='climbs.Color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='climb',
            name='setter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='climbs.Setter'),
            preserve_default=False,
        ),
    ]
