# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-21 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0009_auto_20180321_1124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClimbRoute',
            new_name='Anchor',
        ),
        migrations.RemoveField(
            model_name='boulder',
            name='area',
        ),
        migrations.RemoveField(
            model_name='boulder',
            name='color',
        ),
        migrations.RemoveField(
            model_name='boulder',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='boulder',
            name='setter',
        ),
        migrations.RemoveField(
            model_name='route',
            name='area',
        ),
        migrations.RemoveField(
            model_name='route',
            name='color',
        ),
        migrations.RemoveField(
            model_name='route',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='route',
            name='setter',
        ),
        migrations.DeleteModel(
            name='Boulder',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
