# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-21 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0010_auto_20180321_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climb',
            old_name='climb_route',
            new_name='anchor',
        ),
    ]
