# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-16 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0011_auto_20180321_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSpread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_spread', to='climbs.Area')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_spread', to='climbs.Grade')),
            ],
        ),
    ]
