# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-17 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0012_areaspread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areaspread',
            old_name='quantity',
            new_name='percent',
        ),
    ]
