# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-17 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0013_auto_20180417_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaspread',
            name='percent',
            field=models.FloatField(),
        ),
    ]
