# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-16 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0015_auto_20180418_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setter',
            old_name='name',
            new_name='tag',
        ),
        migrations.AddField(
            model_name='setter',
            name='foreman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foreman_gym', to='climbs.Gym'),
        ),
        migrations.AlterField(
            model_name='setter',
            name='current_gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_gyms', to='climbs.Gym'),
        ),
    ]
