# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-18 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climbs', '0016_auto_20180516_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='climb',
            name='notes',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
